### ISSUE TITLE
Aspect visualization view is broken in Eclipse 2022-03

### ISSUE THREAD

**Issue by marioja** [eclipse/ajdt#34] opened 2023-03-15 21:36 UTC
This commit https://github.com/eclipse/ajdt/commit/e106ca4c203d2ed520dbbbbcf02748142ec6ecaa was applied for the e426 repo but not for the e423.

I have created a fork and have applied it to but I am not sure:

1. how to test it using a local update site
2. how to submit it as a pull request to you guys.

**Comment by kriegaex** [comment] 2023-03-19 10:35
Normally, I do not port fixes back to older AJDT versions, because I simply do not have enough spare time. In this case, I am making an exception, because I messed this up myself in an imperfect refactoring. So I cherry-picked the 2.46 commit onto the 4.23 branch in https://github.com/eclipse/ajdt/commit/f4047f09bc873cbb63f07e59af2b5e1686c31d6c. I pushed it to the 4.23 update site, but it is **untested**. Please let me know if it helps.

**Comment by marioja** [comment] 2023-03-21 02:14
@kriegaex Thanks for doing it.  Will test it in the office tomorrow.  I would have loved to help.

**Comment by kriegaex** [comment] 2023-03-23 07:31
@marioja: Ping!

**Comment by marioja** [comment] 2023-03-23 18:59
I appologize for not responding.  I have see a couple errors and I need to find time to document them.  I will post them here as soon as I have the availability.

**Comment by marioja** [comment] 2023-03-23 23:01
Ok, I installed eclipse 2022-03 +
![image](https://user-images.githubusercontent.com/49068/227381812-f36c9f3e-36cf-4570-8c71-a7435e94f10e.png)
then I imported branch  AJDT_ITD_FAILURE from https://github.com/marioja/sample-tests.git and the first error occurs when I look at PreGreetings.aj:
![image](https://user-images.githubusercontent.com/49068/227382388-9cd11481-c260-4636-9a83-a9df8ed448b1.png)
There are two problems.

1. The aspectj decoration does not appear in the left vertical border of the editor
2. The inter-type definition for greetingsCount is not recognized at line 27 and 28.  The error message is: greetingsCount cannot be resolved or is not a field.  Note that no red decoration appears on the PreGreetings.aj nor any error show up in the Markers view.

The last error is worse.  If I right mouse click the simple-aspectj-ajdt project/AspectJ Tools/Remove AspectJ capability then I right mouse click the same project/Configure/Convert to AspectJ (or add AspectJ nature, I do not recall) then the workspace pops up an error message about a stackoverflow.  I have attached the .metadata/.log from that workspace.

-

**Comment by marioja** [comment] 2023-03-23 23:06
This is the .log file when the stackoverflowerror occurs.  You can see starting on line 89 a recursion call endless loop.
[.metadata/.log](https://github.com/eclipse/ajdt/files/11057072/workspace.log)

**Comment by marioja** [comment] 2023-03-24 01:41
One last thing, if you run mvn clean test then maven will have no problem with any of the project and will handle the PreGreetings.aj correctly.

**Comment by kriegaex** [comment] 2023-03-24 07:18
Please do not mix issues. This one is about the visualisation view. You are now talking about aspect markers.

Please also be careful when switching between different Eclipse and AspectJ versions with the same project without recompiling. Furthermore, be careful to use the correct versions of AJDT and M2E Eclipse for your IDE version. If everything is OK in these respects and you still have a problem in 2022-03, please upgrade to 2022-12 or 2023-03 and check if it works there. I have no intention of maintaining AJDT for older versions, simply because, like I said, I do not have enough sparetime. If you can find someone to sponsor my AspectJ, AJDT and AspectJ Maven work, maybe that would change and I could work less in my daytime job and more on OSS.

**Comment by kriegaex** [comment] 2023-03-24 08:05
I quickly tried in 2023-03, and it looks like this:

![image](https://user-images.githubusercontent.com/1537384/227460891-3340ff29-c14f-4f36-a89a-c8ed1f4e4235.png)

![image](https://user-images.githubusercontent.com/1537384/227460961-5c12bde7-79c1-48ec-b4ef-d99c771513a7.png)

Looks good to me. Running `Main` yields:

![image](https://user-images.githubusercontent.com/1537384/227461059-736ff98e-e1f9-4b88-9744-8b6bcb21bde7.png)

**Comment by kriegaex** [comment] 2023-03-24 08:14
But really, this is off-topic. This issue is about the Aspect Visualisation view.

![image](https://user-images.githubusercontent.com/1537384/227462534-bab21042-a7c3-4762-b03d-48669fd72786.png)

![image](https://user-images.githubusercontent.com/1537384/227462623-20b63281-0e6b-4d05-9c9e-72cc0c9f69a0.png)

**Comment by kriegaex** [comment] 2023-03-24 11:34
Looking at your workspace log, I make a guess and just pushed commit e29d182b7b99ea7b91ce92695c730fbc0fc7f45f, downgrading the AspectJ version packaged into AJDT to 1.9.19 from the latest snapshot used before. The commit comment tells you why. I also published a new AJDT version. Because I do not have any local Eclipse 2023-03 anymore, please try and test it yourself. It would be nice to get AJDT working on 2023-03 again before I really stop maintaining it for good.

**Comment by marioja** [comment] 2023-03-24 13:11
@kriegaex I appreciate what you are doing for 2022-03 and unfortunately, I cannot offer money, just my able body to help.  You mentioned 2023-03 in your comment at 1.5 hours ago.  Did you mean 2022-03? Also in your comment 5 hours ago, you mentioned also 2023-03.  I am assuming that those tests were done on 2023-03 indeed.

As for mixing issues, I put everything in this ticket assuming this is the only you would ever work on.  I can take the time to create a separate one for the stackoverflow, the aspectj markers and the ITD errors.  But that would be 3 issues on 2022-03 which as you said is old and you  might not work on.

If you give me a hint as to where to look for fixes I might have a crack at it myself.  I now know that the update site is created in the releng project and I now can debug using an eclipse launch configuration so I think I can do some level of investigation on my end but I would really appreciate if I could ask some pointed questions.

Last but not least, I thought the commits you cherry picked for the visualization would have fixed the markers/ITD errors.  For my uneducated eyes they all fell in the visualization category.  This is what you get when some uninitiated apprentice tries to play in your world.

**Comment by kriegaex** [comment] 2023-03-24 13:19
> You mentioned 2023-03 in your comment at 1.5 hours ago. Did you mean 2022-03?

Yes, sorry. I updated the comment. I just had 5 minutes during a break, having a cup of tea. I was too hasty and messed up the original comment.

> Also in your comment 5 hours ago, you mentioned also 2023-03. I am assuming that those tests were done on 2023-03 indeed.

Correct.

**Comment by marioja** [comment] 2023-03-24 13:39
I tested with the latest repo and I got this:
![image](https://user-images.githubusercontent.com/49068/227536399-ef58f033-7730-4f45-9b70-ee21a91de319.png)
I will try to specify my requirement to use 1.9.19 specifically.

**Comment by marioja** [comment] 2023-03-24 13:43
This is the only version in your update site:
![image](https://user-images.githubusercontent.com/49068/227537044-6dba9b0a-749e-470d-b16d-c32c187c2f03.png)
Is this the correct one? I.e. did you package AspectJ 1.9.19 as 1.9.20.202303241129?

**Comment by kriegaex** [comment] 2023-03-24 14:06
> Is this the correct one? I.e. did you package AspectJ 1.9.19 as 1.9.20.202303241129?

I guess so. I never fully understood this Tycho stuff, but the current timestamp suggests as much.

Do you have the option to use Eclipse 2023-03 (4.27) or at least 2022-12 (4.26)? I would like to know if you have the same problems there or not.

**Comment by marioja** [comment] 2023-03-24 15:38
I have tested in 2022-12 and 2023-03 and there is no problem with the aspectJ markers or the ITD. I did not test for the infinite recursive loop.  I know there is a lot of messages but I added this to an earlier post.

**Comment by marioja** [comment] 2023-03-24 15:40
> > Is this the correct one? I.e. did you package AspectJ 1.9.19 as 1.9.20.202303241129?
> 
> I guess so. I never fully understood this Tycho stuff, but the current timestamp suggests as much.
> 
Oh, and I thought I was the only one that did not understand this stuff. 😄

**Comment by marioja** [comment] 2023-03-24 16:04
If I may ask another silly question, why in the github action for branch e423 you run the profile e421 whichs looks up from https://download.eclipse.org/releases/2021-09/.  Should it not be https://download.eclipse.org/releases/2022-03/?

**Comment by kriegaex** [comment] 2023-03-25 06:19
> I have tested in 2022-12 and 2023-03 and there is no problem with the aspectJ markers or the ITD. I did not test for the infinite recursive loop. I know there is a lot of messages but I added this to an earlier post.

Sorry, that must have slipped my attention.

> If I may ask another silly question, why in the github action for branch e423 you run the profile e421 whichs looks up from https://download.eclipse.org/releases/2021-09/. Should it not be https://download.eclipse.org/releases/2022-03/?

Because the GitHub action is currently unused. While setting it up, I found out that there is no way to inject the Eclipse signing certificate into the build after migration to GitHub, i.e. I still have to build AJDT on a Jenkins instance which is part of the Eclipse infrastructure and which at the time of setting up the GitHub action I did not have access to yet, because I was not an official committer on the project yet.

**Comment by kriegaex** [comment] 2023-03-25 11:44
I think I managed to reproduce the problem in a new 2022-03 installation. As far as I understand, it was caused by what I explained to you on the phone already: In Eclipse JDT, over the years and as the Java language evolved, the developers adopted more ASCII characters as shorthands for certain types of project and code structures.

It is difficult to explain in a compact way, but they are used in classes  such as [`JavaElement`](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/40fa81de93d65b85d6a8eb8cfc2c381b045bfcd2/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/JavaElement.java#L81-L101) and [`MementoTokenizer`](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/40fa81de93d65b85d6a8eb8cfc2c381b045bfcd2/org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/util/MementoTokenizer.java#L19-L39).

Now AJDT fork extends those classes to [`AspectElement`](https://github.com/eclipse/ajdt/blob/3293bb056a4a9b9003fed8072f0390bf13037e63/org.eclipse.ajdt.core/src/org/eclipse/ajdt/core/javaelements/AspectElement.java#L52-L60) and [`AJMementoTokenizer`](https://github.com/eclipse/ajdt/blob/3293bb056a4a9b9003fed8072f0390bf13037e63/org.eclipse.ajdt.core/src/org/eclipse/ajdt/core/AJMementoTokenizer.java#L42-L51), respectively. The latter two classes had not been updated in a long time, which led to collisions between symbols previously used by AJDT vs. ones more recently used by JDT. Therefore, I moved the AspectJ ones out of the way. They now use symbols currently still unused by JDT. I had fixed that in the _e426_ branch lately, but not back-ported it to _e423_.

After a bit of cherry-picking, I noticed that actually, the _e426_ code of AJDT can be used unchanged for _e423_, so I just rebased and force-pushed, then built AJDT with the _e423_ Maven profile, and it works. Just upgrade from the _e423_ update site, recompile your AspectJ projects (because of the changed symbols for the project element mementoes) and enjoy a working AJDT for Eclipse 2022-03 (4.23). It even includes the latest AspectJ 1.9.20 snapshot, because in AspectJ I also adjusted the symbols, which are used there in a certain part.

I am confident enough to close this issue. We can reopen it, if unexpectedly for you the problem is not solved.

**Closed by kriegaex** 2023-03-25 11:44 UTC
Labels: bug
